"""add author post model

Revision ID: 221187e80863
Revises: 47ed78975eea
Create Date: 2019-10-16 17:55:43.191410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '221187e80863'
down_revision = '47ed78975eea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('author', sa.String(length=64), nullable=True))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'post', 'user', ['user_id'], ['id'])
    op.drop_column('post', 'author')
    # ### end Alembic commands ###
